import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { ApolloWrapper } from "@/graphql/wrapper";
import { Header } from "@/components/header";
import { DeferredHeader } from "@/components/deferred-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  breadcrumbs,
  children,
}: Readonly<{
  breadcrumbs: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ApolloWrapper>
          <div className="bg-white px-10 py-4 h-full w-full">
            <Header />
            <DeferredHeader />
            {children}
          </div>
        </ApolloWrapper>
      </body>
    </html>
  );
}
